---
title: An R Markdown document converted from "16_LongBMI.ipynb"
output: html_document
---

# Preparing BMI trajectories

```{r}
library(readr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr, warn.conflicts = FALSE)
```

```{r}
bmilong <- read_tsv(
    "/ludc/Home/daniel_c/projects/DVA/LongitudinalBMI/data/bmilong.tsv",
    col_types = "n-nn-"
) %>%
    drop_na
head(bmilong)
length(unique(bmilong$eid))
```

```{r}
bmilong <- bmilong %>%
    filter(time >= 0, time <= 5.5) %>%
    group_by(eid) %>%
    filter(any(time == 0) & any(time > 0)) %>%
    ungroup %>%
    arrange(eid, time)
length(unique(bmilong$eid))
```

```{r}
bmilong <- bmilong %>%
    mutate(
        time2 = cut(
            time,
            breaks = c(-Inf, .5, 1.5, 2.5, 3.5, 4.5, 5.5),
            labels = FALSE
        ) - 1
    ) %>%
    group_by(eid) %>%
    filter(any(time2 == 0) & any(time2 > 0)) %>%
    ungroup
head(bmilong)
length(unique(bmilong$eid))
```

```{r}
bmilong <- bmilong %>%
    group_by(eid, time2) %>%
    summarise(bmi2 = median(bmi), .groups = "drop") %>%
    rename_with(~gsub("2", "", .x))
head(bmilong)
length(unique(bmilong$eid))
```

```{r}
write_tsv(bmilong, "../data/bmilong.tsv")
```

